'use client';
// import type { Metadata } from "next";
import { usePathname } from 'next/navigation';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import './page.css';
import ScrollToTop from '@/components/ScrollToTop';
import Nav from '@/components/Navbar/Nav';
import Footer from '@/components/Footer/Footer';
import { useState } from 'react';
import StatsPandaModal from '@/components/Modals/StatsPandaModal';
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const topics = [
  { id: 'LiveCounters', category: 'LiveCounters', label: 'Live Counters' },
  { id: 'UsStates', category: 'UsStates', label: 'U.S. States' },
  { id: 'Countries', category: 'Countries', label: 'Countries' },
  { id: 'EachState', category: 'EachState', label: 'Each State' },
  { id: 'EachCountry', category: 'EachCountry', label: 'Each Country' },
];
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isOpen, setIsOpen] = useState(false);
  const pathname = usePathname();
  return (
    <html lang="en">
      <ScrollToTop />

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased App`}
        style={
          pathname === '/data-topics-landing-page' ||
          pathname === '/topics-home-page'
            ? { paddingTop: 72 }
            : undefined
        }
      >
        <Nav />
        {children}
        <Footer topics={topics} />
        <StatsPandaModal isOpen={isOpen} setIsOpen={setIsOpen} />
      </body>
    </html>
  );
}
